server:
  port: 8002
mybatis:
  type-aliases-package: cn.jcet.springcloud.pojo
  config-location: classpath:mybatis/mybatis-cfg.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
#  spring配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db02?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

#  eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
    instance:
      instance-id: springcloud-provider-dept-8002

#描述
info:
  app.name: xianlei-springcloud
  authon.name: xianlei








